### ISSUE TITLE
Seed database for testing

### ISSUE THREAD

**Issue by diegoalzate** [lexicongovernance/forum-backend#48]
# overview
testing api services is too long: create db data, open frontend etc.

with this we can remove db data overhead

**Comment by MartinBenediktBusch** [comment]
Based on the new data structure the seed database should contain at a minimum (with minimum I mean the minimum requirements in order to test the voting):

- seed event (one is enough) 
- seed cycle (one is enough) 
- seed forum_questions (one is enough)
- seed question_options (at least two)
- seed users (at least one other than yourself)
- seed groups (at least two)

**Comment by MartinBenediktBusch** [comment]
Furthermore, a seed database would allow to simplify the existing test cases since less information must be inserted into the database for each test case.
